# Build on push and PR events
on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
  pull_request:

jobs:
  run-integration-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: "actions/checkout@v3"

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"

      - name: Run Integration Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 33
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck
